<div id="reportViewerModal" class="hidden fixed inset-0 bg-slate-900/60 backdrop-blur-sm flex justify-center items-center z-50 p-4 no-print">
    <div class="bg-white dark:bg-slate-800 rounded-2xl shadow-2xl w-full max-w-3xl max-h-[90vh] flex flex-col animate-premium-in">
        <!-- Progress Bar (Subtle) -->
        <div class="h-1 w-full bg-slate-100 dark:bg-slate-700/50 rounded-t-2xl overflow-hidden">
            <div class="h-full bg-teal-500 w-full"></div>
        </div>

        <div class="printable-area p-10 flex-grow overflow-y-auto">
            <div class="text-center mb-8">
                <h1 class="text-xl font-extrabold text-slate-800 dark:text-white font-display mb-1">Uswag Iloilo City Pharmacy Report</h1>
                <h2 id="reportTypeTitle" class="text-base font-bold text-slate-500 dark:text-slate-400"></h2>
                <div class="h-px w-full bg-slate-100 dark:bg-slate-700 mt-6"></div>
            </div>

            <div id="reportMetadata" class="grid grid-cols-2 gap-x-12 gap-y-3 text-xs mb-8">
                <div class="flex justify-between border-b border-slate-50 dark:border-slate-700 pb-1.5">
                    <span class="font-bold text-slate-400 uppercase tracking-tighter">Report ID:</span>
                    <span id="reportId" class="font-bold text-slate-700 dark:text-slate-200"></span>
                </div>
                <div class="flex justify-between border-b border-slate-50 dark:border-slate-700 pb-1.5">
                    <span class="font-bold text-slate-400 uppercase tracking-tighter">Generated For:</span>
                    <span id="generatedFor" class="font-bold text-slate-700 dark:text-slate-200"></span>
                </div>
                <div class="flex justify-between border-b border-slate-50 dark:border-slate-700 pb-1.5">
                    <span class="font-bold text-slate-400 uppercase tracking-tighter">Generated By:</span>
                    <span id="generatedBy" class="font-bold text-slate-700 dark:text-slate-200"></span>
                </div>
                <div class="flex justify-between border-b border-slate-50 dark:border-slate-700 pb-1.5">
                    <span class="font-bold text-slate-400 uppercase tracking-tighter">Generated Date:</span>
                    <span id="generatedDate" class="font-bold text-slate-700 dark:text-slate-200"></span>
                </div>
            </div>

            <div id="reportContent" class="space-y-8">
                <!-- Data will be injected here via JS -->
            </div>
        </div>

        <div class="flex justify-end space-x-3 p-6 border-t border-slate-100 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-700/30 rounded-b-2xl no-print">
            <button onclick="document.getElementById('reportViewerModal').classList.add('hidden')" class="px-6 py-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600 rounded-xl text-sm font-bold text-slate-600 dark:text-slate-400 hover:bg-slate-50 transition-all shadow-sm">Close</button>
            <button onclick="window.print()" class="px-6 py-2.5 bg-teal-600 hover:bg-teal-700 text-white rounded-xl text-sm font-bold shadow-lg shadow-teal-900/20 flex items-center gap-2 transition-all active:scale-95">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
                Print
            </button>
        </div>
    </div>
</div>

<script>
window.renderReport = function(report) {
    document.getElementById('reportTypeTitle').textContent = report.ReportType;
    document.getElementById('reportId').textContent = report.ReportID;
    document.getElementById('generatedFor').textContent = report.GeneratedForOffice;
    document.getElementById('generatedBy').textContent = report.GeneratedByFullName;
    document.getElementById('generatedDate').textContent = report.GeneratedDate.includes(':') ? report.GeneratedDate : new Date(report.GeneratedDate).toLocaleString();

    const contentDiv = document.getElementById('reportContent');
    contentDiv.innerHTML = '';
    const data = report.data;
    let html = '';

    if (report.ReportType === 'Receipt Confirmation') {
        html += `
            <div class="grid grid-cols-2 gap-x-12 gap-y-4 mb-8">
                <div class="space-y-1">
                    <div class="flex justify-between text-sm"><span class="font-bold text-slate-800">PO Number:</span> <span class="text-slate-600 font-medium">${data.poNumber || 'PO-230003'}</span></div>
                    <div class="flex justify-between text-sm"><span class="font-bold text-slate-800">PO Date:</span> <span class="text-slate-600 font-medium">${data.poDate || '9/15/2023'}</span></div>
                </div>
                <div class="space-y-1">
                    <div class="flex justify-between text-sm"><span class="font-bold text-slate-800">Supplier:</span> <span class="text-slate-600 font-medium">${data.supplierName || 'MedSupply Inc.'}</span></div>
                </div>
            </div>

            <div class="grid grid-cols-2 gap-x-12 mb-8 bg-slate-50 dark:bg-slate-900/50 p-4 rounded-xl border border-slate-100 dark:border-slate-700/50">
                <div class="flex flex-col"><span class="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">Received Date</span> <span class="text-sm font-bold text-slate-700 dark:text-slate-200">${data.receivedDate || '9/20/2023, 6:00:00 PM'}</span></div>
                <div class="flex flex-col"><span class="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">Received By</span> <span class="text-sm font-bold text-slate-700 dark:text-slate-200">${data.receivedBy || 'Warehouse Staff'}</span></div>
            </div>

            <div class="overflow-hidden border border-slate-100 dark:border-slate-700 rounded-xl">
                <table class="w-full text-sm text-left">
                    <thead class="bg-slate-50 dark:bg-slate-900/50 text-slate-800 dark:text-white font-bold">
                        <tr>
                            <th class="px-6 py-4">Item</th>
                            <th class="px-6 py-4 text-center">Ordered</th>
                            <th class="px-6 py-4 text-center">Received</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-50 dark:divide-slate-700/50">
                        <tr class="dark:text-slate-300">
                            <td class="px-6 py-4 font-medium">${data.itemName || 'Amoxicillin 250mg'}</td>
                            <td class="px-6 py-4 text-center font-bold">${(data.quantityOrdered || 1500).toLocaleString()}</td>
                            <td class="px-6 py-4 text-center font-bold text-teal-600">${(data.quantityReceived || 1500).toLocaleString()}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        `;
    } else if (report.ReportType === 'Inventory Valuation') {
        html += `
            <div class="overflow-hidden border border-slate-100 dark:border-slate-700 rounded-xl">
                <table class="w-full text-sm text-left">
                    <thead class="bg-slate-50 dark:bg-slate-900/50 text-slate-800 dark:text-white font-bold">
                        <tr>
                            <th class="px-6 py-4">Item</th>
                            <th class="px-6 py-4 text-center">Quantity</th>
                            <th class="px-6 py-4 text-right">Avg. Cost</th>
                            <th class="px-6 py-4 text-right">Total Value</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-50 dark:divide-slate-700/50">
                        ${(data || []).map(item => `
                            <tr class="dark:text-slate-300">
                                <td class="px-6 py-4 font-medium">${item.itemName}</td>
                                <td class="px-6 py-4 text-center font-bold text-slate-700 dark:text-slate-200">${item.totalQuantity.toLocaleString()}</td>
                                <td class="px-6 py-4 text-right text-slate-500 font-medium">$${item.averageCost.toFixed(2)}</td>
                                <td class="px-6 py-4 text-right font-bold text-teal-600">$${item.totalValue.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</td>
                            </tr>
                        `).join('')}
                    </tbody>
                </table>
            </div>
        `;
    } else if (report.ReportType === 'Stock Card & Ledger') {
        html += `
            <div class="mb-8 p-6 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-100 dark:border-slate-700/50 flex flex-wrap items-center justify-between gap-6">
                <div class="flex items-center gap-4">
                    <div class="p-3 bg-teal-50 dark:bg-teal-900/20 rounded-xl">
                        <svg class="w-6 h-6 text-teal-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"></path></svg>
                    </div>
                    <div>
                        <span class="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-0.5">Item Identity</span>
                        <div class="flex items-baseline gap-2">
                             <span class="text-xl font-extrabold text-slate-800 dark:text-white font-display">${data.itemName || 'Paracetamol 500mg'}</span>
                             <span class="px-2 py-0.5 bg-slate-200 dark:bg-slate-700 text-[10px] font-bold rounded text-slate-600 dark:text-slate-400 uppercase tracking-tighter">${data.itemType || 'Tablet'}</span>
                        </div>
                    </div>
                </div>
                <div class="text-right">
                    <span class="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">On-Hand Inventory</span>
                    <span class="text-2xl font-black text-teal-600">${(data.currentBalance || 7500).toLocaleString()} <span class="text-xs font-bold text-slate-400">UNITS</span></span>
                </div>
            </div>

            <div class="space-y-8">
                <div>
                    <h4 class="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                        <span class="p-1 bg-blue-100 text-blue-600 rounded">IC</span> Current Stock Batches
                    </h4>
                    <div class="overflow-hidden border border-slate-100 dark:border-slate-700 rounded-xl">
                        <table class="w-full text-sm text-left">
                            <thead class="bg-slate-50 dark:bg-slate-900/50 text-slate-800 dark:text-white font-bold">
                                <tr><th class="px-6 py-4">Batch ID</th><th class="px-6 py-4 text-center">Quantity</th><th class="px-6 py-4">Expiry Date</th><th class="px-6 py-4 text-right">Unit Cost</th></tr>
                            </thead>
                            <tbody class="divide-y divide-slate-50 dark:divide-slate-700/50">
                                ${(data.batches || []).map(batch => `
                                    <tr class="dark:text-slate-300">
                                        <td class="px-6 py-4 font-mono text-xs font-bold">${batch.batchId}</td>
                                        <td class="px-6 py-4 text-center font-bold text-slate-700 dark:text-slate-200">${batch.quantity.toLocaleString()}</td>
                                        <td class="px-6 py-4 font-medium text-slate-500">${batch.expiry}</td>
                                        <td class="px-6 py-4 text-right font-medium text-slate-500">$${batch.cost.toFixed(2)}</td>
                                    </tr>
                                `).join('')}
                            </tbody>
                        </table>
                    </div>
                </div>

                <div>
                    <h4 class="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                        <span class="p-1 bg-amber-100 text-amber-600 rounded">TL</span> Transaction Ledger
                    </h4>
                    <div class="overflow-hidden border border-slate-100 dark:border-slate-700 rounded-xl">
                        <table class="w-full text-sm text-left">
                            <thead class="bg-slate-50 dark:bg-slate-900/50 text-slate-800 dark:text-white font-bold">
                                <tr>
                                    <th class="px-6 py-4">Date</th>
                                    <th class="px-6 py-4">Reference & Type</th>
                                    <th class="px-6 py-4 text-center">Batch #</th>
                                    <th class="px-6 py-4 text-center">In</th>
                                    <th class="px-6 py-4 text-center">Out</th>
                                    <th class="px-6 py-4 text-right">Balance</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-slate-50 dark:divide-slate-700/50">
                                ${(data.transactions || []).map(t => `
                                    <tr class="dark:text-slate-300">
                                        <td class="px-6 py-4 text-xs font-bold text-slate-500">${t.date}</td>
                                        <td class="px-6 py-4">
                                            <div class="text-xs font-bold text-slate-800 dark:text-white">${t.type}</div>
                                            <div class="text-[10px] text-slate-400 font-medium tracking-tight">${t.ref}</div>
                                        </td>
                                        <td class="px-6 py-4 text-center text-[10px] font-mono font-bold text-slate-500">${t.batch || 'N/A'}</td>
                                        <td class="px-6 py-4 text-center font-bold ${t.in ? 'text-teal-600' : 'text-slate-300'}">${t.in ? '+' + t.in.toLocaleString() : '-'}</td>
                                        <td class="px-6 py-4 text-center font-bold ${t.out ? 'text-rose-500' : 'text-slate-300'}">${t.out ? '-' + t.out.toLocaleString() : '-'}</td>
                                        <td class="px-6 py-4 text-right font-bold text-slate-800 dark:text-white">${t.balance.toLocaleString()}</td>
                                    </tr>
                                `).join('')}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        `;
    } else {
        html = '<p class="text-center py-10 text-slate-400 font-medium">This report type layout is being optimized.</p>';
    }

    contentDiv.innerHTML = html;
    document.getElementById('reportViewerModal').classList.remove('hidden');
}
</script>
